index:
    path: /
    controller: App\Controller\TweetController::index

ver_tweet:
    path: /tweet/{id}
    controller: App\Controller\TweetController::verTweet

api_get_tweet:
  path: /api/tweets/{id}
  controller: App\Controller\ApiController::getTweet
  methods: ["GET"]

api_get_user:
  path: /api/users/{id}
  controller: App\Controller\ApiController::getTweetfonyUser
  methods: ["GET"]

api_index:
  path: /api
  controller: App\Controller\ApiController::index
  methods: ["GET"]

api_post_user:
  path: /api/users
  controller: App\Controller\ApiController::postTweetfonyUser
  methods: ["POST"]

api_put_user:
  path: /api/users/{id}
  controller: App\Controller\ApiController::putTweetfonyUser
  methods: ["PUT"]

api_get_tweets:
  path: /api/tweets
  controller: App\Controller\ApiController::getTweets
  methods: ["GET"]

api_get_users:
  path: /api/users
  controller: App\Controller\ApiController::getTweetfonyUsers
  methods: ["GET"]

api_post_tweet:
  path: /api/tweets
  controller: App\Controller\ApiController::postTweet
  methods: ["POST"]

api_put_tweet:
  path: /api/tweets/{id}
  controller: App\Controller\ApiController::putTweet
  methods: ["PUT"]

api_delete_tweet:
  path: /api/tweets/{id}
  controller: App\Controller\ApiController::deleteTweet
  methods: ["DELETE"]

api_delete_user:
  path: /api/users/{id}
  controller: App\Controller\ApiController::deleteTweetfonyUser
  methods: ["DELETE"]